name: quiz_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.6
  fl_chart: ^0.68.0
  confetti: ^0.7.0 # If you are using the confetti results screen

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # This is the crucial part to add
  assets:
    - assets/questions.json
    - assets/lessons.json
